---
- name: Create Elastic IP address
  hosts: localhost
  connection: local
  become: false
  vars:
    region: us-east-1

  tasks:
    - name: Allocate Elastic IP address
      ec2_eip:
        region: "{{ region }}"
      register: eip

    - name: Print Elastic IP address
      debug:
        var: eip.public_ip

