---
- hosts: aws
  become: yes
  tasks:
    - name: Perform update
      command: sudo apt-get update

    - name: move to keyrings folder
      command: sudo mkdir -p /etc/apt/keyrings


    - name: Add Docker repository
      apt_repository:
              repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
              state: present

    - name: Perform Update
      command: sudo apt-get update ; clear

    - name: Install Docker
      command: sudo apt-get install -y docker-ce

    - name: Install Docker daemon
      command: sudo wget https://raw.githubusercontent.com/lerndevops/labs/master/kubernetes/0-install/daemon.json -P /etc/docker

    - name: Restart Docker Service
      command: sudo systemctl restart docker.service

