- name: Provision EC2 instance
  hosts: localhost
  gather_facts: no
  vars:
    keypair: cap-key1
    region: us-east-1
    zone: us-east-1d
    instance_type: t2.micro
    ami_id: ami-0557a15b87f6559cf
  tasks:
  - name: Create EC2 instance
    ec2:
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      region: "{{ region }}"
      count: 2
      instance_tags:
             name: simplilearn
      vpc_subnet_id: subnet-0a055bfd59c3adbee
      assign_public_ip: yes
    register: ec2

  - name: Add new instance to host group
    add_host:
      name: "{{ item.public_ip }}"
      groups: launched
    with_items: "{{ ec2.instances }}"

  - name: Print the public IP addresses
    debug:
      var: item.public_ip
    with_items: "{{ ec2.instances }}"
