---
- hosts: kubernetes-master
  become: true
  tasks:
    - name: Install calico network plugin     
      shell: sudo  kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

