---
- name: Install Docker
  hosts: all
  become: true
  roles:
    - role: geerlingguy.docker
      docker_install_compose: false

- name: Install Kubernetes
  hosts: kubernetes-master
  become: true
  vars:
    kube_version: "{{ kubernetes_version }}"
    kubelet_extra_args: "--node-ip={{ hostvars[inventory_hostname]['ansible_host'] }}"
  roles:
    - role: geerlingguy.kubernetes
      kubernetes_network_plugin: calico
      kubernetes_enable_dashboard: true

- name: Join worker nodes to the cluster
  hosts: kubernetes-worker
  become: true
  vars:
    kube_version: "{{ kubernetes_version }}"
    kubelet_extra_args: "--node-ip={{ hostvars[inventory_hostname]['ansible_host'] }}"
  roles:
    - role: geerlingguy.kubernetes
      kubernetes_join: true
      kubernetes_master_url: "https://{{ groups['kubernetes-master'][0] }}:6443"
      kubernetes_network_plugin: calico

