- name: Take etcd backup
  hosts: localhost
  become: true
  vars:
    backup_dir: "/var/etcd-backup"
    etcdctl_path: "/usr/local/bin/etcdctl"
  tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
    - name: Take etcd snapshot
      shell: "{{ etcdctl_path }} snapshot save {{ backup_dir }}/etcd-$(date +%Y-%m-%d_%H:%M:%S).db"

