kind: Service
apiVersion: v1 
metadata:
  name: myapp2
  namespace: default 
  #labels: # are optional 
spec:
  type: NodePort # will publish a hostport/nodeport on every node/vm in the cluster ans also creates an 
                 # internal virutal load balancer(kube will create dynamically lb ip) that can forward the request into a single/group of pods
  selector: 
    app: myapp2
  ports:
    - name: http
      port: 80  ## this is the port we are assinging to the LB created by kube 
      targetPort: 3000 # this is the port of the app inside the container 

